WebApp/Models/PoleInfo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoleInfo
    {
        public PoleInfo()
        {
            this.PoleImages = new HashSet<PoleImage>();
        }
    
        public int ID { get; set; }
        public string PoleID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> TaskAddeddate { get; set; }
        public Nullable<System.DateTime> TaskPerformeddate { get; set; }
        public Nullable<int> TaskAssainUserID { get; set; }
        public string ImageMapPath { get; set; }
        public Nullable<double> AdjacentPoleHeight { get; set; }
        public string TransFormerLoading { get; set; }
        public string Notes { get; set; }
        public string ImagesTakenpath { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> TaskCompleteDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual PoleType PoleType { get; set; }
        public virtual UserInformation UserInformation { get; set; }
        public virtual UserInformation UserInformation1 { get; set; }
        public virtual ICollection<PoleImage> PoleImages { get; set; }
    }
}

WebApp/Controllers/PoleInfoController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Xml;
using WebApp.Models;
using Microsoft.AspNet.Identity;
namespace WebApp.Controllers
{
    
    public class PoleInfoController : Controller
    {
        PoleInfoEntities objE = new PoleInfoEntities();
        private UserInformation userInfo { get; set; }

        //
        // GET: /PoleInfo/
        public ActionResult Index()
        {
            userInfo = new UserInformationController().GetUserByAspNetUserId(User.Identity.GetUserId());
            var data = GetSearchData(userInfo);
            
            return View(data);
        }

        //
        // GET: /PoleInfo/Details/5
        public ActionResult Details(int id)
        {
            PoleInfoEntities objE = new PoleInfoEntities();
            var data = (from p in objE.PoleInfoes.Where(p => p.ID == id)
                        join t in objE.PoleTypes on p.TypeID equals t.ID
                        select new PoleInfoViewModel
                        {
                            ID = p.ID,
                            PoleID = p.PoleID,
                            TypeID = p.TypeID,
                            TypeName=t.TypeName,
                            TaskAddeddate = p.TaskAddeddate,
                            TaskPerformeddate = p.TaskPerformeddate,
                            ImageMapPath = p.ImageMapPath,
                            AdjacentPoleHeight = p.AdjacentPoleHeight,
                            TransFormerLoading = p.TransFormerLoading,
                            Notes = p.Notes,
                            ImagesTakenpath = p.ImagesTakenpath
                        }).SingleOrDefault();
            return View(data);
        }

        //
        // GET: /PoleInfo/Create
        public ActionResult Create()
        {
            //PoleInfoEntities objE = new PoleInfoEntities();
            ViewBag.PoleType = new SelectList(objE.PoleTypes.ToList(), "ID", "TypeName");
            string aID = User.Identity.GetUserId();
            ViewBag.TaskAssainUser = new SelectList(new UserInformationController().GetDropdownData(aID), "ID", "UserFullName");
            return View();
        }

        //
        // POST: /PoleInfo/Create
        [HttpPost]
        public ActionResult Create(PoleInfoViewModel PoleInfo, HttpPostedFileBase file)
        {
            string ImageMapPath = "";
            string ImagesTakenpath = "";
            try
            {
                // TODO: Add insert logic here

                PoleInfo obj = new PoleInfo();
                obj.PoleID = PoleInfo.PoleID;
                obj.TypeID = PoleInfo.TypeID;
                obj.TaskAddeddate = PoleInfo.TaskAddeddate;
                obj.TaskPerformeddate = PoleInfo.TaskPerformeddate;

                obj.AdjacentPoleHeight = PoleInfo.AdjacentPoleHeight;
                obj.TransFormerLoading = PoleInfo.TransFormerLoading;
                obj.Notes = PoleInfo.Notes;

                //obj.UserID = User.Identity.GetUserId();
                //PoleInfoEntities objE = new PoleInfoEntities();
                var FileSavePathList = objE.FileSavePaths.ToList();

                if (Request.Files["ImageMapPathfile"].ContentLength > 0)
                {
                    var _file = Request.Files["ImageMapPathfile"];
                    string _savepath = FileSavePathList.SingleOrDefault(p => p.FileFor == "PoleImageMapPath").FilePath;
                    string fileExtension = System.IO.Path.GetExtension(_file.FileName);
                    ImageMapPath = _savepath + PoleInfo.PoleID.ToString().Trim() + "_MapImage" + fileExtension;

                    if (!System.IO.Directory.Exists(_savepath))
                    {
                        System.IO.Directory.CreateDirectory(_savepath);
                    }
                    _file.SaveAs(ImageMapPath);
                }

                if (Request.Files["ImagesTakenpathfile"].ContentLength > 0)
                {
                    var _file = Request.Files["ImagesTakenpathfile"];
                    string _savepath = FileSavePathList.SingleOrDefault(p => p.FileFor == "PoleImagesTakenpath").FilePath;
                    string fileExtension = System.IO.Path.GetExtension(_file.FileName);
                    ImagesTakenpath = _savepath + PoleInfo.PoleID.ToString().Trim() + "_TakenImages" + fileExtension;
                    if (!System.IO.Directory.Exists(_savepath))
                    {
                        System.IO.Directory.CreateDirectory(_savepath);
                    }
                    _file.SaveAs(ImagesTakenpath);
                }
                obj.ImageMapPath = ImageMapPath;
                obj.ImagesTakenpath = ImagesTakenpath;
                obj.TaskAssainUserID = PoleInfo.TaskAssainUserID;
                var userbasic = new UserInformationController().GetUserByAspNetUserId(User.Identity.GetUserId());
                obj.UserID = userbasic.Id;
                
                
                obj.IsActive = true;
                obj.CreateDate = DateTime.Now;

                int Id = Save(obj);

                return RedirectToAction("Index");
            }
            catch
            {
                DeleteFile(ImageMapPath);
                DeleteFile(ImagesTakenpath);
                return View();
            }
        }

        //
        // GET: /PoleInfo/Edit/5
        public ActionResult Edit(int id)
        {

            //PoleInfoEntities objE = new PoleInfoEntities();
            var data = (from p in objE.PoleInfoes.Where(p=>p.ID==id).ToList()
                        select new PoleInfoViewModel
                        {
                            ID = p.ID,
                            PoleID = p.PoleID,
                            TypeID = p.TypeID,
                            TaskAddeddate = p.TaskAddeddate,
                            TaskPerformeddate = p.TaskPerformeddate,
                            ImageMapPath = p.ImageMapPath,
                            AdjacentPoleHeight = p.AdjacentPoleHeight,
                            TransFormerLoading=p.TransFormerLoading,
                            Notes = p.Notes,
                            ImagesTakenpath = p.ImagesTakenpath,

                            TaskAssainUserID=p.TaskAssainUserID,
                            UserID=p.UserID,

                        }).SingleOrDefault();

            ViewBag.PoleType = new SelectList(objE.PoleTypes.ToList(), "ID", "TypeName", data.TypeID);
            string aID = User.Identity.GetUserId();
            ViewBag.TaskAssainUser = new SelectList(new UserInformationController().GetDropdownData(aID), "ID", "UserFullName", data.TaskAssainUserID);
            return View(data);
        }

        //
        // POST: /PoleInfo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, PoleInfoViewModel PoleInfo)
        {
            try
            {
                // TODO: Add update logic here

                PoleInfo obj = new PoleInfo();
                obj.PoleID = PoleInfo.PoleID;
                obj.TypeID = PoleInfo.TypeID;
                obj.TaskAddeddate = PoleInfo.TaskAddeddate;
                obj.TaskPerformeddate = PoleInfo.TaskPerformeddate;
                obj.ImageMapPath = PoleInfo.ImageMapPath;
                obj.AdjacentPoleHeight = PoleInfo.AdjacentPoleHeight;
                obj.TransFormerLoading = PoleInfo.TransFormerLoading;
                obj.Notes = PoleInfo.Notes;
                obj.ImagesTakenpath = PoleInfo.ImagesTakenpath;
                obj.TaskAssainUserID = PoleInfo.TaskAssainUserID;
                obj.UpdateDate = DateTime.Now;

                //obj.UserID = User.Identity.GetUserId();
                //PoleInfoEntities objE = new PoleInfoEntities();
                var FileSavePathList = objE.FileSavePaths.ToList();

                if (Request.Files["ImageMapPathfile"].ContentLength > 0)
                {
                    var _file = Request.Files["ImageMapPathfile"];
                    string _savepath = FileSavePathList.SingleOrDefault(p => p.FileFor == "PoleImageMapPath").FilePath;
                    string fileExtension = System.IO.Path.GetExtension(_file.FileName);
                    string ImageMapPath = _savepath + PoleInfo.PoleID.ToString().Trim() + "_MapImage" + fileExtension;
                    _file.SaveAs(ImageMapPath);
                    obj.ImageMapPath = ImageMapPath;
                }

                if (Request.Files["ImagesTakenpathfile"].ContentLength > 0)
                {
                    var _file = Request.Files["ImagesTakenpathfile"];
                    string _savepath = FileSavePathList.SingleOrDefault(p => p.FileFor == "PoleImagesTakenpath").FilePath;
                    string fileExtension = System.IO.Path.GetExtension(_file.FileName);
                    string ImagesTakenpath = _savepath + PoleInfo.PoleID.ToString().Trim() + "_TakenImages" + fileExtension;
                    _file.SaveAs(ImagesTakenpath);
                    obj.ImagesTakenpath = ImagesTakenpath;
                }
                
                
                int Id = Save(obj);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /PoleInfo/Delete/5
        public ActionResult Delete(int id)
        {
            PoleInfoEntities objE = new PoleInfoEntities();
            var data = (from p in objE.PoleInfoes.Where(p => p.ID == id)
                        join t in objE.PoleTypes on p.TypeID equals t.ID
                        select new PoleInfoViewModel
                        {
                            ID = p.ID,
                            PoleID = p.PoleID,

WebApp/Views/PoleInfo/Create.cshtml
@model WebApp.Models.PoleInfoViewModel

@{
    ViewBag.Title = "Create";
}
@section scripts {
@Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

  $("document").ready(function () {
      $("#TaskAddeddate").datepicker();
      $("#TaskPerformeddate").datepicker();
  });

    </script>

}

<h2 style="text-align:center">Pole Information</h2>

@using (Html.BeginForm("Create", "PoleInfo", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true)



        <div class="form-group">
            @Html.LabelFor(model => model.PoleID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PoleID)
                @Html.ValidationMessageFor(model => model.PoleID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TypeID, (SelectList)ViewBag.PoleType)
                @Html.ValidationMessageFor(model => model.TypeID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskAssainUserID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TaskAssainUserID, (SelectList)ViewBag.TaskAssainUser)
                @Html.ValidationMessageFor(model => model.TaskAssainUserID)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TaskAddeddate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskAddeddate)
                
                @Html.ValidationMessageFor(model => model.TaskAddeddate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskPerformeddate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskPerformeddate)
                @Html.ValidationMessageFor(model => model.TaskPerformeddate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageMapPath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ImageMapPath)
                @Html.ValidationMessageFor(model => model.ImageMapPath)*@
                <input type="file" name="ImageMapPathfile" value="Select Excel File" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdjacentPoleHeight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdjacentPoleHeight)
                @Html.ValidationMessageFor(model => model.AdjacentPoleHeight)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransFormerLoading, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransFormerLoading)
                @Html.ValidationMessageFor(model => model.TransFormerLoading)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes)
                @Html.ValidationMessageFor(model => model.Notes)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagesTakenpath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ImagesTakenpath)
                @Html.ValidationMessageFor(model => model.ImagesTakenpath)*@
                <input type="file" name="ImagesTakenpathfile" value="Select Excel File" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebApp/Views/PoleInfo/Delete.cshtml
@model WebApp.Models.PoleInfoViewModel

@{
    ViewBag.Title = "Delete";
}

<h2 style="text-align:center">Pole Information</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    @Html.ActionLink("Back to List", "Index")
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.PoleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoleID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskAddeddate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskAddeddate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskPerformeddate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskPerformeddate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageMapPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMapPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdjacentPoleHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdjacentPoleHeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransFormerLoading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransFormerLoading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagesTakenpath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagesTakenpath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
            
        </div>
    }
</div>

WebApp/Views/PoleInfo/Details.cshtml
@model WebApp.Models.PoleInfoViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PoleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoleID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskAddeddate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskAddeddate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskPerformeddate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskPerformeddate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageMapPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMapPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdjacentPoleHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdjacentPoleHeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransFormerLoading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransFormerLoading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagesTakenpath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagesTakenpath)
        </dd>

    </dl>
</div>

WebApp/Views/PoleInfo/Edit.cshtml
@model WebApp.Models.PoleInfoViewModel

@{
    ViewBag.Title = "Edit";
}

<h2 style="text-align:center">Pole Information</h2>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">

    $("document").ready(function () {
        $("#TaskAddeddate").datepicker();
        $("#TaskPerformeddate").datepicker();
        //$("#PoleID")
    });

</script>
}



@using (Html.BeginForm("Edit", "PoleInfo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)


        <div class="form-group">
            @Html.LabelFor(model => model.PoleID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PoleID, new { @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.PoleID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskAssainUserID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TaskAssainUserID, (SelectList)ViewBag.TaskAssainUser)
                @Html.ValidationMessageFor(model => model.TaskAssainUserID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TypeID, (SelectList)ViewBag.PoleType)
                @Html.ValidationMessageFor(model => model.TypeID)
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.TaskAddeddate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskAddeddate)
                @Html.ValidationMessageFor(model => model.TaskAddeddate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskPerformeddate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskPerformeddate)
                @Html.ValidationMessageFor(model => model.TaskPerformeddate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageMapPath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageMapPath)
                <input type="file" name="ImageMapPathfile" value="Select Excel File" />
                @Html.ValidationMessageFor(model => model.ImageMapPath)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdjacentPoleHeight, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdjacentPoleHeight)
                @Html.ValidationMessageFor(model => model.AdjacentPoleHeight)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransFormerLoading, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransFormerLoading)
                @Html.ValidationMessageFor(model => model.TransFormerLoading)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes)
                @Html.ValidationMessageFor(model => model.Notes)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagesTakenpath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagesTakenpath)
                <input type="file" name="ImagesTakenpathfile" value="Select Excel File" />
                @Html.ValidationMessageFor(model => model.ImagesTakenpath)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebApp/Views/PoleInfo/Import.cshtml
@model WebApp.Models.PoleInfoViewModel

@{
    ViewBag.Title = "Import";
}

<h2 style="text-align:center">Pole Information Import</h2>


@using (Html.BeginForm("Import", "PoleInfo", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="file" name="file" value="Select Excel File" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskAssainUserID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TaskAssainUserID, (SelectList)ViewBag.TaskAssainUser)
                @Html.ValidationMessageFor(model => model.TaskAssainUserID)
            </div>
        </div>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Import" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp/Views/PoleInfo/Index.cshtml
@model IEnumerable<WebApp.Models.PoleInfoViewModel>

@{
    ViewBag.Title = "Index";
}

<h2 style="text-align:center">Pole Information</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Import Excel Data", "Import")
</p>

<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.PoleID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserFullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TaskAddeddate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TaskPerformeddate)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.AdjacentPoleHeight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PoleID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserFullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TaskAddeddate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TaskPerformeddate)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.AdjacentPoleHeight)
        </td>

        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>