WebApp/Models/PoleImage.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoleImage
    {
        public long ID { get; set; }
        public Nullable<int> PoleInfoID { get; set; }
        public string ImageMapPath { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual PoleInfo PoleInfo { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}

WebApp/Controllers/PoleImageController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Drawing;

namespace WebApp.Controllers
{
    public class PoleImageController : Controller
    {
        private PoleInfoEntities db = new PoleInfoEntities();
        private UserInformation userInfo { get; set; }
        // GET: /PoleImage/
        public ActionResult Index()
        {
            //TempData["userInfo"] = new UserInformationController().GetUserByAspNetUserId(User.Identity.GetUserId());
            //userInfo = TempData["userInfo"] as UserInformation ;
            userInfo = new UserInformationController().GetUserByAspNetUserId(User.Identity.GetUserId());
            //var poleimages = db.PoleImages.Include(p => p.PoleInfo).Include(p => p.UserInformation);
            List<PoleImageViewModel> poleimglist = new List<PoleImageViewModel>();
            //foreach(var itm in poleimages)
            //{
            //    PoleImageViewModel obj = new PoleImageViewModel();

            //}

            var data = (from p in db.PoleImages
                        join pt in db.PoleInfoes on p.PoleInfoID equals pt.ID
                        where (userInfo.UserTypeID == 1 || p.UserID == userInfo.Id)
                        select new PoleImageViewModel
                        {
                            ID = p.ID,
                            PoleInfoID=(int)p.PoleInfoID,
                            ImageMapPath=p.ImageMapPath,
                            //ImageBase64=PoleClass.ImageToBase64(p.ImageMapPath),
                            Notes=p.Notes,
                            PoleID = pt.PoleID

                        }).ToList().OrderByDescending(p => p.ID);

          

            return View(data);
        }

        // GET: /PoleImage/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PoleImage poleimage = db.PoleImages.Find(id);
            if (poleimage == null)
            {
                return HttpNotFound();
            }
            return View(poleimage);
        }

        // GET: /PoleImage/Create
        public ActionResult Create()
        {

            ViewBag.PoleInfoID = new SelectList(GetPoleIDList(), "ID", "PoleID");
            ViewBag.UserID = new SelectList(db.UserInformations, "Id", "UserFullName");
            return View();
        }

        // POST: /PoleImage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PoleImage poleimage, FormCollection collection)
        {
            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];
            }
            //, IEnumerable files
            //var userbasic = new UserInformationController().GetUserByAspNetUserId(User.Identity.GetUserId());
            userInfo = TempData["userInfo"] as UserInformation;
            if (ModelState.IsValid)
            {
                poleimage.UserID = userInfo.Id;
                //db.PoleImages.Add(poleimage);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PoleInfoID = new SelectList(GetPoleIDList(), "ID", "PoleID", poleimage.PoleInfoID);
            ViewBag.UserID = new SelectList(db.UserInformations, "Id", "UserFullName", poleimage.UserID);
            return View(poleimage);
        }

        // GET: /PoleImage/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PoleImage poleimage = db.PoleImages.Find(id);
            if (poleimage == null)
            {
                return HttpNotFound();
            }
            ViewBag.PoleInfoID = new SelectList(db.PoleInfoes, "ID", "PoleID", poleimage.PoleInfoID);
            ViewBag.UserID = new SelectList(db.UserInformations, "Id", "UserFullName", poleimage.UserID);
            return View(poleimage);
        }

        // POST: /PoleImage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,PoleInfoID,ImageMapPath,UserID,Notes,CreateDate,UpdateDate")] PoleImage poleimage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(poleimage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PoleInfoID = new SelectList(db.PoleInfoes, "ID", "PoleID", poleimage.PoleInfoID);
            ViewBag.UserID = new SelectList(db.UserInformations, "Id", "UserFullName", poleimage.UserID);
            return View(poleimage);
        }

        // GET: /PoleImage/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PoleImage poleimage = db.PoleImages.Find(id);
            if (poleimage == null)
            {
                return HttpNotFound();
            }
            return View(poleimage);
        }

        // POST: /PoleImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            PoleImage poleimage = db.PoleImages.Find(id);
            db.PoleImages.Remove(poleimage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult UploadFiles(IEnumerable files, PoleImage poleimage)
        {
            string TempPath = Server.MapPath("~/Content/TempFile/");
            userInfo = new UserInformationController().GetUserByAspNetUserId(User.Identity.GetUserId());
            //List<PoleImage> objlist = new List<PoleImage>();
            foreach (HttpPostedFileBase file in files)
            {
                string filePath = Path.Combine(TempPath, file.FileName);
                //System.IO.File.WriteAllBytes(filePath, ReadData(file.InputStream));

                //PoleImage obj = new PoleImage();
                poleimage.UserID = userInfo.Id;
                //db.PoleImages.Add(poleimage);
                //db.SaveChanges();
            }

            return Json("All files have been successfully stored.");
        }

        private byte[] ReadData(Stream stream)
        {
            byte[] buffer = new byte[16 * 1024];

            using (MemoryStream ms = new MemoryStream())
            {
                int read;
                while ((read = stream.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }

                return ms.ToArray();
            }
        }

        public ActionResult SaveUploadedFile()        
        {
            bool isSavedSuccessfully = true;
            string fName = "";
            try
            {
                foreach (string fileName in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fileName];
                    //Save file content goes here
                    fName = Guid.NewGuid().ToString(); //file.FileName;
                    if (file != null && file.ContentLength > 0)
                    {

                        var originalDirectory = new System.IO.DirectoryInfo(string.Format("{0}Images\\uploaded", Server.MapPath(@"\")));
                        string pathString = System.IO.Path.Combine(originalDirectory.ToString(), "imagepath");
                        var fileName1 = System.IO.Path.GetFileName(file.FileName);
                        bool isExists = System.IO.Directory.Exists(pathString);
                        if (!isExists)
                            System.IO.Directory.CreateDirectory(pathString);
                        var path = string.Format("{0}\\{1}", pathString, file.FileName);

                        //if (System.IO.File.Exists(path))
                        //{

                        //    System.IO.File.Delete(path);
                        //}

                        //file.SaveAs(path);
                    }
                }
            }
            catch (Exception ex)
            {
                isSavedSuccessfully = false;
            }

            if (isSavedSuccessfully)
                return Json(new { Message = fName });
            else
                return Json(new { Message = "Error in saving file" });
        }

        public ActionResult SaveUploadedPoleImage(List<PoleImageList> obj)
        {
            try
            {
                if(obj==null)
                {
                    return Json(new { Success = 3, ID = 0, ex = "" });
                }

                string PoleID="";
                PoleInfoEntities objE = new PoleInfoEntities();
                var FileSavePathList = objE.FileSavePaths.ToList();
                string _savepath = FileSavePathList.SingleOrDefault(p => p.FileFor == "PoleImageMapPath").FilePath;

WebApp/Views/PoleImage/Create.cshtml
@model WebApp.Models.PoleImage

@{
    ViewBag.Title = "Create";
}
@section Scripts {

    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/dropzonescss")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/dropzonescripts")
}
<h2>Create</h2>
<script>
    $(document).ready(function () {

    });


    function Save() {

        if (dropzoneForm.children.length == 0)
        {
            alert("NO Image Found to save");
            return;
        }

        var PoleImage = { "ID": "", "PoleID": "", "PoleInfoID": "", "Image64": "" };
        var PoleImages=[]

        var selectedPoleId = $("#PoleInfoID :selected").text();
        var vPoleInfoID = $("#PoleInfoID :selected").val();
        for (var i = 1; i < dropzoneForm.children.length; i++) {
            var imagediv = dropzoneForm.children[i];
            var img64 = imagediv.getElementsByTagName("img")[0].src

            PoleImage.ID = i;
            PoleImage.PoleID = selectedPoleId;
            PoleImage.PoleInfoID = vPoleInfoID;
            PoleImage.Image64 = img64;
            PoleImages.push(PoleImage);

            var PoleImage ={"ID": "", "PoleID": "", "Image64": ""};
        }

        $.ajax({
            url: '/PoleImage/SaveUploadedPoleImage',
            data: JSON.stringify(PoleImages),
            type: 'POST',
            contentType: 'application/json;',
            dataType: 'json',
            success: function (result) {

                debugger;
                if (result.Success == "1") {
                    alert('Successfully Saved Pole Image');
                }
                else if (result.Success == "3") {
                    alert('No Image Found to Save');
                }
                else {
                    alert("Error Occured In Transaction");
                }
            }
        });
    }

</script>

@using (Html.BeginForm("Create", "PoleImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pole Image Upload </h4>
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.PoleInfoID, "PoleInfoID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PoleInfoID", String.Empty)
                @Html.ValidationMessageFor(model => model.PoleInfoID)
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Save" class="btn btn-default" onclick="Save()" />
            </div>
        </div>
    </div>

}



@Html.FileUploadForm("../PoleImage/SaveUploadedFile")

WebApp/Views/PoleImage/Create2.cshtml
@model WebApp.Models.PoleImage

@{
    ViewBag.Title = "Create";
}


<style type="text/css">
    #dropZone {
        background: gray;
        border: black dashed 3px;
        width: 200px;
        padding: 50px;
        text-align: center;
        color: white;
    }
</style>

@section scripts {
@Scripts.Render("~/bundles/modernizr")
@Styles.Render("~/Content/dropzonescss")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/dropzonescripts")



<script>



</script>
}
@using (Html.BeginForm("Create", "PoleImage", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(i => i.ImageMapPath)
    <div class="form-horizontal">
        <h4>Pole Image</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group" >
            @Html.LabelFor(model => model.PoleInfoID, "PoleInfoID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PoleInfoID, (SelectList)ViewBag.PoleInfoID, String.Empty)
                @Html.ValidationMessageFor(model => model.PoleInfoID)
            </div>
        </div>



        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@*<script>
    $(document).ready(function () {
        alert("Test")
        $('#btnSubmit').bind('click', function (e) {
            alert("Test")
        });
    })
</script>*@

@*@Html.FileUploadForm("../PoleImage/SaveUploadedFile")*@


@*<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="btnSubmit" />
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@


    @*<script type="text/javascript">
        Dropzone.options.dropzoneForm = {
            init: function () {
                var myDropzone = this;
                this.on("complete", function (data) {
                    var res = JSON.parse(data.xhr.responseText);
                    console.log(res.Message);
                });
            }
        };
    </script>*@

WebApp/Views/PoleImage/Delete.cshtml
@model WebApp.Models.PoleImage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PoleImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageMapPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMapPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PoleInfo.PoleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoleInfo.PoleID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserInformation.AspNetUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserInformation.AspNetUserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApp/Views/PoleImage/Details.cshtml
@model WebApp.Models.PoleImage

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PoleImage</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImageMapPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMapPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PoleInfo.PoleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PoleInfo.PoleID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserInformation.AspNetUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserInformation.AspNetUserId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApp/Views/PoleImage/Edit.cshtml
@model WebApp.Models.PoleImage

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PoleImage</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PoleInfoID, "PoleInfoID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PoleInfoID", String.Empty)
                @Html.ValidationMessageFor(model => model.PoleInfoID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageMapPath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageMapPath)
                @Html.ValidationMessageFor(model => model.ImageMapPath)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", String.Empty)
                @Html.ValidationMessageFor(model => model.UserID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes)
                @Html.ValidationMessageFor(model => model.Notes)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate)
                @Html.ValidationMessageFor(model => model.CreateDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdateDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdateDate)
                @Html.ValidationMessageFor(model => model.UpdateDate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApp/Views/PoleImage/Index.cshtml
@model IEnumerable<WebApp.Models.PoleImageViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PoleID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageMapPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdateDate)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PoleID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageMapPath)
            @*<img src="@Url.Content(@item.ImageMapPath)" alt="No Image" />*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Notes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdateDate)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>